apiVersion: v2
name: open-webui
description: "A User-Friendly Web Interface for Chat Interactions \U0001F44B"
type: application
version: 2.1.31
appVersion: 0.6.42
projectUrl: https://github.com/open-webui/open-webui
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
