apiVersion: v2
name: commafeed
description: A RSS Aggregator
type: application
version: 8.1.1
appVersion: 6.1.1
projectUrl: https://github.com/athou/commafeed
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
