apiVersion: v2
name: commafeed
description: A RSS Aggregator
type: application
version: 9.0.1
appVersion: 7.0.0
projectUrl: https://github.com/athou/commafeed
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
