apiVersion: v2
name: commafeed
description: A RSS Aggregator
type: application
version: 8.0.3
appVersion: 6.0.0
projectUrl: https://github.com/athou/commafeed
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
