apiVersion: v2
name: ghost
description: A simple, powerful publishing platform that allows you to share your stories with the world.
type: application
version: 8.9.1
appVersion: 6.9.1
projectUrl: https://github.com/TryGhost/Ghost
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
