apiVersion: v2
name: paperless-ngx
description: A community-supported supercharged version of paperless; scan, index and archive all your physical documents
type: application
version: 7.6.2
appVersion: 2.20.2
projectUrl: https://github.com/paperless-ngx/paperless-ngx
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
