apiVersion: v2
name: keycloak
description: A identity and access management solution for modern applications and services
type: application
version: 1.4.3
appVersion: 26.5.3
projectUrl: https://github.com/keycloak/keycloak
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
