apiVersion: v2
name: vikunja
description: A self hosted task management application
type: application
version: 8.0.3
appVersion: 1.1.0
projectUrl: https://github.com/go-vikunja/vikunja
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
