apiVersion: v2
name: radicale
description: A simple CalDAV (calendar) and CardDAV (contact) server
type: application
version: 4.0.8
appVersion: 3.5.10.0
projectUrl: https://github.com/tomsquest/docker-radicale
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
