apiVersion: v2
name: maddy
description: A self hosted minimal mail server
type: application
version: 4.0.1
appVersion: 0.8.2
projectUrl: https://github.com/foxcpp/maddy
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
