apiVersion: v2
name: redmine
description: A project management web application
type: application
version: 7.3.2
appVersion: 6.1.0
projectUrl: https://hub.docker.com/_/redmine
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
