apiVersion: v2
name: codimd
description: A self hosted markdown compatible note taking app
type: application
version: 7.2.2
appVersion: 2.6.1
projectUrl: https://github.com/hackmdio/codimd
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
