apiVersion: v2
name: memos
description: A self hosted note taking app
type: application
version: 7.3.1
appVersion: 0.26.1
projectUrl: https://github.com/usememos/memos
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
