apiVersion: v2
name: memos
description: A self hosted note taking app
type: application
version: 7.2.3
appVersion: 0.25.3
projectUrl: https://github.com/usememos/memos
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
