apiVersion: v2
name: vaultwarden
description: A self hosted password manager
type: application
version: 7.3.3
appVersion: 1.35.3
projectUrl: https://github.com/dani-garcia/vaultwarden
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
