apiVersion: v2
name: miniflux
description: Miniflux is a minimalist RSS feed reader
type: application
version: 1.1.3
appVersion: 2.2.15
projectUrl: https://github.com/miniflux/v2
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
